/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LoginResult {
  'token' : SessionToken,
  'isAdmin' : boolean,
}

export interface AdminUserInfo {
  'username' : string,
  'displayName' : string,
  'banExpiresAt' : [] | [Time],
  'isVerified' : boolean,
  'isBanned' : boolean,
}
export interface CallRequestWithStatus {
  'id' : bigint,
  'status' : CallStatus,
  'timestamp' : Time,
  'callee' : Principal,
  'caller' : Principal,
}
export type CallStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'ended' : null } |
  { 'accepted' : null };
export interface Comment {
  'id' : bigint,
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : bigint,
}
export interface ConversationSummary {
  'lastMessageIsRead' : boolean,
  'lastMessageSender' : string,
  'otherUsername' : string,
  'lastMessage' : string,
  'unreadCount' : bigint,
  'lastTimestamp' : Time,
  'otherDisplayName' : string,
}
export interface DirectMessage {
  'id' : bigint,
  'text' : string,
  'senderUsername' : string,
  'isRead' : boolean,
  'timestamp' : Time,
  'recipientUsername' : string,
}
export type ExternalBlob = Uint8Array;
export interface LocalCallRequest {
  'id' : bigint,
  'status' : CallStatus,
  'callerUsername' : string,
  'timestamp' : Time,
  'calleeUsername' : string,
}
export interface LocalUser {
  'age' : bigint,
  'username' : string,
  'displayName' : string,
  'lastNameChange' : [] | [Time],
  'passwordHash' : string,
  'photo' : [] | [ExternalBlob],
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface Notification {
  'id' : bigint,
  'postText' : [] | [string],
  'callRequestId' : [] | [bigint],
  'actorName' : string,
  'notifType' : NotificationType,
  'isRead' : boolean,
  'timestamp' : Time,
  'recipientUsername' : string,
  'postId' : [] | [bigint],
}
export type NotificationType = { 'like' : null } |
  { 'comment' : null } |
  { 'callRequest' : null };
export interface Post {
  'id' : bigint,
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export interface ProfileSettings {
  'hideFollowers' : boolean,
  'hideFollowing' : boolean,
}
export type SessionToken = bigint;
export interface Signal {
  'id' : bigint,
  'data' : string,
  'toUsername' : string,
  'timestamp' : Time,
  'fromUsername' : string,
  'signalType' : string,
}
export type Time = bigint;
export interface User {
  'fname' : string,
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'photo' : [] | [ExternalBlob],
  'telephone' : string,
}
export interface UserProfile {
  'fname' : string,
  'name' : string,
  'photo' : [] | [ExternalBlob],
  'telephone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VoiceParticipant {
  'username' : string,
  'displayName' : string,
  'isMicActive' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptCallRequest' : ActorMethod<[bigint], undefined>,
  'acceptCallRequestAsLocal' : ActorMethod<[SessionToken, bigint], undefined>,
  'addComment' : ActorMethod<[bigint, string], bigint>,
  'addCommentAsLocal' : ActorMethod<[SessionToken, bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banLocalUser' : ActorMethod<[SessionToken, string], undefined>,
  'banLocalUserWithDuration' : ActorMethod<
    [SessionToken, string, bigint],
    undefined
  >,
  'blockUser' : ActorMethod<[SessionToken, string], undefined>,
  'checkIsWildfireAdmin' : ActorMethod<[SessionToken], boolean>,
  'clearCallTopic' : ActorMethod<[SessionToken], undefined>,
  'createPost' : ActorMethod<[string], bigint>,
  'createPostAsLocal' : ActorMethod<[SessionToken, string], bigint>,
  'createUser' : ActorMethod<[string, string, string], undefined>,
  'deleteCallRequest' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteCommentAsLocal' : ActorMethod<[SessionToken, bigint], undefined>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'deletePostAsLocal' : ActorMethod<[SessionToken, bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'denyCallRequest' : ActorMethod<[bigint], undefined>,
  'denyCallRequestAsLocal' : ActorMethod<[SessionToken, bigint], undefined>,
  'endCall' : ActorMethod<[bigint], undefined>,
  'endCallAsLocal' : ActorMethod<[SessionToken, bigint], undefined>,
  'followUser' : ActorMethod<[SessionToken, string], undefined>,
  'getAllUsersForAdmin' : ActorMethod<[SessionToken], Array<AdminUserInfo>>,
  'getBanExpiry' : ActorMethod<[string], [] | [Time]>,
  'getBlockedUsers' : ActorMethod<[SessionToken], Array<string>>,
  'getCallRequest' : ActorMethod<[bigint], [] | [CallRequestWithStatus]>,
  'getCallRequests' : ActorMethod<[], Array<CallRequestWithStatus>>,
  'getCallRequestsAsLocal' : ActorMethod<
    [SessionToken],
    Array<LocalCallRequest>
  >,
  'getCallTopic' : ActorMethod<[string], [] | [string]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsForPost' : ActorMethod<[bigint], Array<Comment>>,
  'getCommentsForPostAsLocal' : ActorMethod<
    [SessionToken, bigint],
    Array<Comment>
  >,
  'getConversations' : ActorMethod<[SessionToken], Array<ConversationSummary>>,
  'getDirectMessages' : ActorMethod<
    [SessionToken, string],
    Array<DirectMessage>
  >,
  'getFollowers' : ActorMethod<[SessionToken, string], Array<string>>,
  'getFollowing' : ActorMethod<[SessionToken, string], Array<string>>,
  'getLocalUserProfile' : ActorMethod<[SessionToken], [] | [LocalUser]>,
  'getLocalUsers' : ActorMethod<[], Array<LocalUser>>,
  'getMessage' : ActorMethod<[bigint], [] | [Message]>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getMessagesAsLocal' : ActorMethod<[SessionToken], Array<Message>>,
  'getMySignals' : ActorMethod<[SessionToken], Array<Signal>>,
  'getNotificationsAsLocal' : ActorMethod<[SessionToken], Array<Notification>>,
  'getOnlineUsernames' : ActorMethod<[], Array<string>>,
  'getPostLikes' : ActorMethod<[bigint], Array<string>>,
  'getPostLikesAsLocal' : ActorMethod<[SessionToken, bigint], Array<string>>,
  'getPosts' : ActorMethod<[], Array<Post>>,
  'getPostsAsLocal' : ActorMethod<[SessionToken], Array<Post>>,
  'getProfileSettings' : ActorMethod<[SessionToken], ProfileSettings>,
  'getProfileVisitors' : ActorMethod<
    [SessionToken, string],
    { 'visitors' : Array<string>, 'count' : bigint }
  >,
  'getPublicProfileSettings' : ActorMethod<[string], ProfileSettings>,
  'getUnreadDMCount' : ActorMethod<[SessionToken], bigint>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserBio' : ActorMethod<[string], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStatus' : ActorMethod<[string], [] | [string]>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'getUsersCount' : ActorMethod<[], bigint>,
  'getVoiceParticipants' : ActorMethod<[SessionToken], Array<VoiceParticipant>>,
  'grantVerifiedBadge' : ActorMethod<[SessionToken, string], undefined>,
  'isBlocked' : ActorMethod<[SessionToken, string], boolean>,
  'isBlockedBy' : ActorMethod<[SessionToken, string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[SessionToken, string], boolean>,
  'isUserBanned' : ActorMethod<[string], boolean>,
  'isUserVerified' : ActorMethod<[string], boolean>,
  'joinVoiceChannel' : ActorMethod<[SessionToken], Array<VoiceParticipant>>,
  'leaveVoiceChannel' : ActorMethod<[SessionToken], undefined>,
  'likePost' : ActorMethod<[bigint], undefined>,
  'likePostAsLocal' : ActorMethod<[SessionToken, bigint], undefined>,
  'loginLocalAccount' : ActorMethod<[string, string], { token: SessionToken; isAdmin: boolean }>,
  'logoutLocalAccount' : ActorMethod<[SessionToken], undefined>,
  'markAllNotificationsReadAsLocal' : ActorMethod<[SessionToken], undefined>,
  'markDirectMessagesRead' : ActorMethod<[SessionToken, string], undefined>,
  'markNotificationReadAsLocal' : ActorMethod<
    [SessionToken, bigint],
    undefined
  >,
  'pingOnline' : ActorMethod<[SessionToken], undefined>,
  'recordProfileVisit' : ActorMethod<[SessionToken, string], undefined>,
  'registerLocalAccount' : ActorMethod<
    [string, string, string, bigint, [] | [ExternalBlob]],
    undefined
  >,
  'revokeVerifiedBadge' : ActorMethod<[SessionToken, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendCallRequest' : ActorMethod<[Principal], bigint>,
  'sendCallRequestAsLocal' : ActorMethod<[SessionToken, string], bigint>,
  'sendDirectMessage' : ActorMethod<[SessionToken, string, string], bigint>,
  'sendMessage' : ActorMethod<[string], bigint>,
  'sendMessageAsLocal' : ActorMethod<[SessionToken, string], bigint>,
  'sendSignal' : ActorMethod<[SessionToken, string, string, string], undefined>,
  'setCallTopic' : ActorMethod<[SessionToken, string], undefined>,
  'setMicActive' : ActorMethod<[SessionToken, boolean], undefined>,
  'setUserStatus' : ActorMethod<[SessionToken, string], undefined>,
  'unbanLocalUser' : ActorMethod<[SessionToken, string], undefined>,
  'unblockUser' : ActorMethod<[SessionToken, string], undefined>,
  'unfollowUser' : ActorMethod<[SessionToken, string], undefined>,
  'unlikePost' : ActorMethod<[bigint], undefined>,
  'unlikePostAsLocal' : ActorMethod<[SessionToken, bigint], undefined>,
  'updateLocalUserBio' : ActorMethod<[SessionToken, string], undefined>,
  'updateLocalUserDisplayName' : ActorMethod<[SessionToken, string], string>,
  'updateLocalUserPhoto' : ActorMethod<[SessionToken, ExternalBlob], undefined>,
  'updateProfileSettings' : ActorMethod<
    [SessionToken, boolean, boolean],
    undefined
  >,
  'updateUser' : ActorMethod<[ExternalBlob], undefined>,
  'updateUserWithoutPhoto' : ActorMethod<[string, string, string], undefined>,
  'validateSessionToken' : ActorMethod<[SessionToken], [] | [string]>,
  'verifyUser' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];