/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionToken = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AdminUserInfo = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'banExpiresAt' : IDL.Opt(Time),
  'email' : IDL.Opt(IDL.Text),
  'isVerified' : IDL.Bool,
  'isBanned' : IDL.Bool,
});
export const CallStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'ended' : IDL.Null,
  'accepted' : IDL.Null,
});
export const CallRequestWithStatus = IDL.Record({
  'id' : IDL.Nat,
  'status' : CallStatus,
  'timestamp' : Time,
  'callee' : IDL.Principal,
  'caller' : IDL.Principal,
});
export const LocalCallRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : CallStatus,
  'callerUsername' : IDL.Text,
  'timestamp' : Time,
  'calleeUsername' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'fname' : IDL.Text,
  'name' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'telephone' : IDL.Text,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const ConversationSummary = IDL.Record({
  'lastMessageIsRead' : IDL.Bool,
  'lastMessageSender' : IDL.Text,
  'otherUsername' : IDL.Text,
  'lastMessage' : IDL.Text,
  'unreadCount' : IDL.Nat,
  'lastTimestamp' : Time,
  'otherDisplayName' : IDL.Text,
});
export const DirectMessage = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'senderUsername' : IDL.Text,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
  'recipientUsername' : IDL.Text,
});
export const LocalUser = IDL.Record({
  'age' : IDL.Nat,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'lastNameChange' : IDL.Opt(Time),
  'passwordHash' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const MessageReaction = IDL.Record({
  'emoji' : IDL.Text,
  'timestamp' : Time,
  'reactorUsername' : IDL.Text,
});
export const Signal = IDL.Record({
  'id' : IDL.Nat,
  'data' : IDL.Text,
  'toUsername' : IDL.Text,
  'timestamp' : Time,
  'fromUsername' : IDL.Text,
  'signalType' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'like' : IDL.Null,
  'comment' : IDL.Null,
  'callRequest' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'postText' : IDL.Opt(IDL.Text),
  'callRequestId' : IDL.Opt(IDL.Nat),
  'actorName' : IDL.Text,
  'notifType' : NotificationType,
  'isRead' : IDL.Bool,
  'timestamp' : Time,
  'recipientUsername' : IDL.Text,
  'postId' : IDL.Opt(IDL.Nat),
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const ProfileSettings = IDL.Record({
  'hideFollowers' : IDL.Bool,
  'hideFollowing' : IDL.Bool,
});
export const User = IDL.Record({
  'fname' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'photo' : IDL.Opt(ExternalBlob),
  'telephone' : IDL.Text,
});
export const VoiceParticipant = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'isMicActive' : IDL.Bool,
});

export const idlService = IDL.Service({
  'acceptCallRequest' : IDL.Func([IDL.Nat], [], []),
  'acceptCallRequestAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addCommentAsLocal' : IDL.Func(
      [SessionToken, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addMessageReaction' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [], []),
  'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banLocalUser' : IDL.Func([SessionToken, IDL.Text], [], []),
  'banLocalUserWithDuration' : IDL.Func(
      [SessionToken, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'blockUser' : IDL.Func([SessionToken, IDL.Text], [], []),
  'checkIsWildfireAdmin' : IDL.Func([SessionToken], [IDL.Bool], ['query']),
  'clearCallTopic' : IDL.Func([SessionToken], [], []),
  'createPost' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createPostAsLocal' : IDL.Func([SessionToken, IDL.Text], [IDL.Nat], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteCallRequest' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteCommentAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'deleteDirectMessage' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'deletePostAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'denyCallRequest' : IDL.Func([IDL.Nat], [], []),
  'denyCallRequestAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'endCall' : IDL.Func([IDL.Nat], [], []),
  'endCallAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'followUser' : IDL.Func([SessionToken, IDL.Text], [], []),
  'getAllUsersForAdmin' : IDL.Func(
      [SessionToken],
      [IDL.Vec(AdminUserInfo)],
      ['query'],
    ),
  'getBanExpiry' : IDL.Func([IDL.Text], [IDL.Opt(Time)], ['query']),
  'getBlockedUsers' : IDL.Func([SessionToken], [IDL.Vec(IDL.Text)], ['query']),
  'getCallRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(CallRequestWithStatus)],
      ['query'],
    ),
  'getCallRequests' : IDL.Func([], [IDL.Vec(CallRequestWithStatus)], ['query']),
  'getCallRequestsAsLocal' : IDL.Func(
      [SessionToken],
      [IDL.Vec(LocalCallRequest)],
      ['query'],
    ),
  'getCallTopic' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCommentsForPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getCommentsForPostAsLocal' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'getConversations' : IDL.Func(
      [SessionToken],
      [IDL.Vec(ConversationSummary)],
      ['query'],
    ),
  'getDirectMessages' : IDL.Func(
      [SessionToken, IDL.Text],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getFollowers' : IDL.Func(
      [SessionToken, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [SessionToken, IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getLocalUserProfile' : IDL.Func(
      [SessionToken],
      [IDL.Opt(LocalUser)],
      ['query'],
    ),
  'getLocalUsers' : IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
  'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
  'getMessageReactions' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Vec(MessageReaction)],
      ['query'],
    ),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getMessagesAsLocal' : IDL.Func(
      [SessionToken],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getMySignals' : IDL.Func([SessionToken], [IDL.Vec(Signal)], []),
  'getNotificationsAsLocal' : IDL.Func(
      [SessionToken],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getOnlineUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPinnedMessage' : IDL.Func(
      [SessionToken, IDL.Text],
      [IDL.Opt(DirectMessage)],
      ['query'],
    ),
  'getPostLikes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'getPostLikesAsLocal' : IDL.Func(
      [SessionToken, IDL.Nat],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getPostsAsLocal' : IDL.Func([SessionToken], [IDL.Vec(Post)], ['query']),
  'getProfileSettings' : IDL.Func([SessionToken], [ProfileSettings], ['query']),
  'getProfileVisitors' : IDL.Func(
      [SessionToken, IDL.Text],
      [IDL.Record({ 'visitors' : IDL.Vec(IDL.Text), 'count' : IDL.Nat })],
      ['query'],
    ),
  'getProfileWithSocial' : IDL.Func(
      [SessionToken, IDL.Text],
      [
        IDL.Record({
          'isVerified' : IDL.Bool,
          'isFollowing' : IDL.Bool,
          'followerCount' : IDL.Nat,
          'followingCount' : IDL.Nat,
          'profile' : IDL.Opt(LocalUser),
        }),
      ],
      ['query'],
    ),
  'getPublicProfileSettings' : IDL.Func(
      [IDL.Text],
      [ProfileSettings],
      ['query'],
    ),
  'getReshareCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTypingStatus' : IDL.Func([SessionToken, IDL.Text], [IDL.Bool], ['query']),
  'getUnreadDMCount' : IDL.Func([SessionToken], [IDL.Nat], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserBadges' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
  'getUserBio' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStatus' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUsersForMatching' : IDL.Func(
      [SessionToken],
      [IDL.Vec(LocalUser)],
      ['query'],
    ),
  'getVoiceParticipants' : IDL.Func(
      [SessionToken],
      [IDL.Vec(VoiceParticipant)],
      ['query'],
    ),
  'grantVerifiedBadge' : IDL.Func([SessionToken, IDL.Text], [], []),
  'isBlocked' : IDL.Func([SessionToken, IDL.Text], [IDL.Bool], ['query']),
  'isBlockedBy' : IDL.Func([SessionToken, IDL.Text], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([SessionToken, IDL.Text], [IDL.Bool], ['query']),
  'isUserBanned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isUserVerified' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'joinVoiceChannel' : IDL.Func(
      [SessionToken],
      [IDL.Vec(VoiceParticipant)],
      [],
    ),
  'leaveVoiceChannel' : IDL.Func([SessionToken], [], []),
  'likePost' : IDL.Func([IDL.Nat], [], []),
  'likePostAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'loginLocalAccount' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Record({ 'token' : SessionToken, 'isAdmin' : IDL.Bool })],
      [],
    ),
  'logoutLocalAccount' : IDL.Func([SessionToken], [], []),
  'markAllNotificationsReadAsLocal' : IDL.Func([SessionToken], [], []),
  'markDirectMessagesRead' : IDL.Func([SessionToken, IDL.Text], [], []),
  'markNotificationReadAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'pinDirectMessage' : IDL.Func([SessionToken, IDL.Text, IDL.Nat], [], []),
  'pingOnline' : IDL.Func([SessionToken], [], []),
  'recordProfileVisit' : IDL.Func([SessionToken, IDL.Text], [], []),
  'registerLocalAccount' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'removeMessageReaction' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [], []),
  'resetPasswordAsAdmin' : IDL.Func([SessionToken, IDL.Text, IDL.Text], [], []),
  'resharePost' : IDL.Func([SessionToken, IDL.Nat], [IDL.Nat], []),
  'revokeVerifiedBadge' : IDL.Func([SessionToken, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendCallRequest' : IDL.Func([IDL.Principal], [IDL.Nat], []),
  'sendCallRequestAsLocal' : IDL.Func([SessionToken, IDL.Text], [IDL.Nat], []),
  'sendDirectMessage' : IDL.Func(
      [SessionToken, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'sendMessageAsLocal' : IDL.Func([SessionToken, IDL.Text], [IDL.Nat], []),
  'sendSignal' : IDL.Func([SessionToken, IDL.Text, IDL.Text, IDL.Text], [], []),
  'setCallTopic' : IDL.Func([SessionToken, IDL.Text], [], []),
  'setMicActive' : IDL.Func([SessionToken, IDL.Bool], [], []),
  'setTypingStatus' : IDL.Func([SessionToken, IDL.Text, IDL.Bool], [], []),
  'setUserEmail' : IDL.Func([SessionToken, IDL.Text], [], []),
  'setUserStatus' : IDL.Func([SessionToken, IDL.Text], [], []),
  'trackCallActivity' : IDL.Func([SessionToken], [], []),
  'unbanLocalUser' : IDL.Func([SessionToken, IDL.Text], [], []),
  'unblockUser' : IDL.Func([SessionToken, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([SessionToken, IDL.Text], [], []),
  'unlikePost' : IDL.Func([IDL.Nat], [], []),
  'unlikePostAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
  'updateLocalUserBio' : IDL.Func([SessionToken, IDL.Text], [], []),
  'updateLocalUserDisplayName' : IDL.Func(
      [SessionToken, IDL.Text],
      [IDL.Text],
      [],
    ),
  'updateLocalUserPhoto' : IDL.Func([SessionToken, ExternalBlob], [], []),
  'updateProfileSettings' : IDL.Func(
      [SessionToken, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'updateUser' : IDL.Func([ExternalBlob], [], []),
  'updateUserWithoutPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'validateSessionToken' : IDL.Func(
      [SessionToken],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'verifyUser' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionToken = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AdminUserInfo = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'banExpiresAt' : IDL.Opt(Time),
    'email' : IDL.Opt(IDL.Text),
    'isVerified' : IDL.Bool,
    'isBanned' : IDL.Bool,
  });
  const CallStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'ended' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const CallRequestWithStatus = IDL.Record({
    'id' : IDL.Nat,
    'status' : CallStatus,
    'timestamp' : Time,
    'callee' : IDL.Principal,
    'caller' : IDL.Principal,
  });
  const LocalCallRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : CallStatus,
    'callerUsername' : IDL.Text,
    'timestamp' : Time,
    'calleeUsername' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'fname' : IDL.Text,
    'name' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'telephone' : IDL.Text,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const ConversationSummary = IDL.Record({
    'lastMessageIsRead' : IDL.Bool,
    'lastMessageSender' : IDL.Text,
    'otherUsername' : IDL.Text,
    'lastMessage' : IDL.Text,
    'unreadCount' : IDL.Nat,
    'lastTimestamp' : Time,
    'otherDisplayName' : IDL.Text,
  });
  const DirectMessage = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'senderUsername' : IDL.Text,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
    'recipientUsername' : IDL.Text,
  });
  const LocalUser = IDL.Record({
    'age' : IDL.Nat,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'lastNameChange' : IDL.Opt(Time),
    'passwordHash' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const MessageReaction = IDL.Record({
    'emoji' : IDL.Text,
    'timestamp' : Time,
    'reactorUsername' : IDL.Text,
  });
  const Signal = IDL.Record({
    'id' : IDL.Nat,
    'data' : IDL.Text,
    'toUsername' : IDL.Text,
    'timestamp' : Time,
    'fromUsername' : IDL.Text,
    'signalType' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'like' : IDL.Null,
    'comment' : IDL.Null,
    'callRequest' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'postText' : IDL.Opt(IDL.Text),
    'callRequestId' : IDL.Opt(IDL.Nat),
    'actorName' : IDL.Text,
    'notifType' : NotificationType,
    'isRead' : IDL.Bool,
    'timestamp' : Time,
    'recipientUsername' : IDL.Text,
    'postId' : IDL.Opt(IDL.Nat),
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
  });
  const ProfileSettings = IDL.Record({
    'hideFollowers' : IDL.Bool,
    'hideFollowing' : IDL.Bool,
  });
  const User = IDL.Record({
    'fname' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'photo' : IDL.Opt(ExternalBlob),
    'telephone' : IDL.Text,
  });
  const VoiceParticipant = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'isMicActive' : IDL.Bool,
  });
  
  return IDL.Service({
    'acceptCallRequest' : IDL.Func([IDL.Nat], [], []),
    'acceptCallRequestAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addCommentAsLocal' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addMessageReaction' : IDL.Func([SessionToken, IDL.Nat, IDL.Text], [], []),
    'assignRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banLocalUser' : IDL.Func([SessionToken, IDL.Text], [], []),
    'banLocalUserWithDuration' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'blockUser' : IDL.Func([SessionToken, IDL.Text], [], []),
    'checkIsWildfireAdmin' : IDL.Func([SessionToken], [IDL.Bool], ['query']),
    'clearCallTopic' : IDL.Func([SessionToken], [], []),
    'createPost' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createPostAsLocal' : IDL.Func([SessionToken, IDL.Text], [IDL.Nat], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteCallRequest' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteCommentAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'deleteDirectMessage' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'deletePostAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'denyCallRequest' : IDL.Func([IDL.Nat], [], []),
    'denyCallRequestAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'endCall' : IDL.Func([IDL.Nat], [], []),
    'endCallAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'followUser' : IDL.Func([SessionToken, IDL.Text], [], []),
    'getAllUsersForAdmin' : IDL.Func(
        [SessionToken],
        [IDL.Vec(AdminUserInfo)],
        ['query'],
      ),
    'getBanExpiry' : IDL.Func([IDL.Text], [IDL.Opt(Time)], ['query']),
    'getBlockedUsers' : IDL.Func(
        [SessionToken],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getCallRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(CallRequestWithStatus)],
        ['query'],
      ),
    'getCallRequests' : IDL.Func(
        [],
        [IDL.Vec(CallRequestWithStatus)],
        ['query'],
      ),
    'getCallRequestsAsLocal' : IDL.Func(
        [SessionToken],
        [IDL.Vec(LocalCallRequest)],
        ['query'],
      ),
    'getCallTopic' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCommentsForPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getCommentsForPostAsLocal' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getConversations' : IDL.Func(
        [SessionToken],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getLocalUserProfile' : IDL.Func(
        [SessionToken],
        [IDL.Opt(LocalUser)],
        ['query'],
      ),
    'getLocalUsers' : IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
    'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
    'getMessageReactions' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Vec(MessageReaction)],
        ['query'],
      ),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getMessagesAsLocal' : IDL.Func(
        [SessionToken],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getMySignals' : IDL.Func([SessionToken], [IDL.Vec(Signal)], []),
    'getNotificationsAsLocal' : IDL.Func(
        [SessionToken],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getOnlineUsernames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPinnedMessage' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Opt(DirectMessage)],
        ['query'],
      ),
    'getPostLikes' : IDL.Func([IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'getPostLikesAsLocal' : IDL.Func(
        [SessionToken, IDL.Nat],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getPostsAsLocal' : IDL.Func([SessionToken], [IDL.Vec(Post)], ['query']),
    'getProfileSettings' : IDL.Func(
        [SessionToken],
        [ProfileSettings],
        ['query'],
      ),
    'getProfileVisitors' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Record({ 'visitors' : IDL.Vec(IDL.Text), 'count' : IDL.Nat })],
        ['query'],
      ),
    'getProfileWithSocial' : IDL.Func(
        [SessionToken, IDL.Text],
        [
          IDL.Record({
            'isVerified' : IDL.Bool,
            'isFollowing' : IDL.Bool,
            'followerCount' : IDL.Nat,
            'followingCount' : IDL.Nat,
            'profile' : IDL.Opt(LocalUser),
          }),
        ],
        ['query'],
      ),
    'getPublicProfileSettings' : IDL.Func(
        [IDL.Text],
        [ProfileSettings],
        ['query'],
      ),
    'getReshareCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTypingStatus' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'getUnreadDMCount' : IDL.Func([SessionToken], [IDL.Nat], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserBadges' : IDL.Func([IDL.Text], [IDL.Vec(IDL.Text)], ['query']),
    'getUserBio' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStatus' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUsersForMatching' : IDL.Func(
        [SessionToken],
        [IDL.Vec(LocalUser)],
        ['query'],
      ),
    'getVoiceParticipants' : IDL.Func(
        [SessionToken],
        [IDL.Vec(VoiceParticipant)],
        ['query'],
      ),
    'grantVerifiedBadge' : IDL.Func([SessionToken, IDL.Text], [], []),
    'isBlocked' : IDL.Func([SessionToken, IDL.Text], [IDL.Bool], ['query']),
    'isBlockedBy' : IDL.Func([SessionToken, IDL.Text], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([SessionToken, IDL.Text], [IDL.Bool], ['query']),
    'isUserBanned' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isUserVerified' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'joinVoiceChannel' : IDL.Func(
        [SessionToken],
        [IDL.Vec(VoiceParticipant)],
        [],
      ),
    'leaveVoiceChannel' : IDL.Func([SessionToken], [], []),
    'likePost' : IDL.Func([IDL.Nat], [], []),
    'likePostAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'loginLocalAccount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Record({ 'token' : SessionToken, 'isAdmin' : IDL.Bool })],
        [],
      ),
    'logoutLocalAccount' : IDL.Func([SessionToken], [], []),
    'markAllNotificationsReadAsLocal' : IDL.Func([SessionToken], [], []),
    'markDirectMessagesRead' : IDL.Func([SessionToken, IDL.Text], [], []),
    'markNotificationReadAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'pinDirectMessage' : IDL.Func([SessionToken, IDL.Text, IDL.Nat], [], []),
    'pingOnline' : IDL.Func([SessionToken], [], []),
    'recordProfileVisit' : IDL.Func([SessionToken, IDL.Text], [], []),
    'registerLocalAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'removeMessageReaction' : IDL.Func(
        [SessionToken, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'resetPasswordAsAdmin' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'resharePost' : IDL.Func([SessionToken, IDL.Nat], [IDL.Nat], []),
    'revokeVerifiedBadge' : IDL.Func([SessionToken, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendCallRequest' : IDL.Func([IDL.Principal], [IDL.Nat], []),
    'sendCallRequestAsLocal' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'sendDirectMessage' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'sendMessageAsLocal' : IDL.Func([SessionToken, IDL.Text], [IDL.Nat], []),
    'sendSignal' : IDL.Func(
        [SessionToken, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setCallTopic' : IDL.Func([SessionToken, IDL.Text], [], []),
    'setMicActive' : IDL.Func([SessionToken, IDL.Bool], [], []),
    'setTypingStatus' : IDL.Func([SessionToken, IDL.Text, IDL.Bool], [], []),
    'setUserEmail' : IDL.Func([SessionToken, IDL.Text], [], []),
    'setUserStatus' : IDL.Func([SessionToken, IDL.Text], [], []),
    'trackCallActivity' : IDL.Func([SessionToken], [], []),
    'unbanLocalUser' : IDL.Func([SessionToken, IDL.Text], [], []),
    'unblockUser' : IDL.Func([SessionToken, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([SessionToken, IDL.Text], [], []),
    'unlikePost' : IDL.Func([IDL.Nat], [], []),
    'unlikePostAsLocal' : IDL.Func([SessionToken, IDL.Nat], [], []),
    'updateLocalUserBio' : IDL.Func([SessionToken, IDL.Text], [], []),
    'updateLocalUserDisplayName' : IDL.Func(
        [SessionToken, IDL.Text],
        [IDL.Text],
        [],
      ),
    'updateLocalUserPhoto' : IDL.Func([SessionToken, ExternalBlob], [], []),
    'updateProfileSettings' : IDL.Func(
        [SessionToken, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'updateUser' : IDL.Func([ExternalBlob], [], []),
    'updateUserWithoutPhoto' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'validateSessionToken' : IDL.Func(
        [SessionToken],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'verifyUser' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };