/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CallRequest {
  'id' : bigint,
  'timestamp' : Time,
  'callee' : Principal,
  'caller' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'text' : string,
  'authorName' : string,
  'author' : Principal,
  'timestamp' : Time,
}
export type Time = bigint;
export interface User {
  'fname' : string,
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
  'photo' : [] | [ExternalBlob],
  'telephone' : string,
}
export interface UserProfile {
  'fname' : string,
  'name' : string,
  'photo' : [] | [ExternalBlob],
  'telephone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface LocalUser {
  'username': string;
  'displayName': string;
  'passwordHash': string;
  'age': bigint;
  'photo': [] | [ExternalBlob];
}
export interface Post {
  'id': bigint;
  'author': Principal;
  'authorName': string;
  'text': string;
  'timestamp': Time;
}
export interface Comment {
  'id': bigint;
  'postId': bigint;
  'author': Principal;
  'authorName': string;
  'text': string;
  'timestamp': Time;
}
export interface VoiceParticipant {
  'username': string;
  'displayName': string;
  'isMicActive': boolean;
}
export interface Signal {
  'id': bigint;
  'fromUsername': string;
  'toUsername': string;
  'signalType': string;
  'data': string;
  'timestamp': Time;
}
export type NotificationType = { 'like': null } | { 'comment': null } | { 'callRequest': null };
export interface Notification {
  'id': bigint;
  'recipientUsername': string;
  'notifType': NotificationType;
  'actorName': string;
  'postId': [] | [bigint];
  'postText': [] | [string];
  'callRequestId': [] | [bigint];
  'timestamp': Time;
  'isRead': boolean;
}
export interface DirectMessage {
  'id': bigint;
  'senderUsername': string;
  'recipientUsername': string;
  'text': string;
  'timestamp': Time;
  'isRead': boolean;
}
export interface ConversationSummary {
  'otherUsername': string;
  'otherDisplayName': string;
  'lastMessage': string;
  'lastTimestamp': Time;
  'unreadCount': bigint;
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUser' : ActorMethod<[string, string, string], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getCallRequest' : ActorMethod<[bigint], [] | [CallRequest]>,
  'getCallRequests' : ActorMethod<[], Array<CallRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessage' : ActorMethod<[bigint], [] | [Message]>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'getUsersCount' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'verifyUser' : ActorMethod<[], undefined>,
  'registerLocalAccount': ActorMethod<[string, string, string, bigint, [] | [ExternalBlob]], undefined>;
  'loginLocalAccount': ActorMethod<[string, string], bigint>;
  'logoutLocalAccount': ActorMethod<[bigint], undefined>;
  'validateSessionToken': ActorMethod<[bigint], [] | [string]>;
  'getLocalUserProfile': ActorMethod<[bigint], [] | [LocalUser]>;
  'updateLocalUserPhoto': ActorMethod<[bigint, ExternalBlob], undefined>;
  'getLocalUsers': ActorMethod<[], Array<LocalUser>>;
  'sendMessageAsLocal': ActorMethod<[bigint, string], bigint>;
  'getMessagesAsLocal': ActorMethod<[bigint], Array<Message>>;
  'sendDirectMessage': ActorMethod<[bigint, string, string], bigint>;
  'getDirectMessages': ActorMethod<[bigint, string], Array<DirectMessage>>;
  'getConversations': ActorMethod<[bigint], Array<ConversationSummary>>;
  'markDirectMessagesRead': ActorMethod<[bigint, string], undefined>;
  'getUnreadDMCount': ActorMethod<[bigint], bigint>;
  'createPostAsLocal': ActorMethod<[bigint, string], bigint>;
  'getPostsAsLocal': ActorMethod<[bigint], Array<Post>>;
  'deletePostAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'likePostAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'unlikePostAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'getPostLikesAsLocal': ActorMethod<[bigint, bigint], Array<string>>;
  'addCommentAsLocal': ActorMethod<[bigint, bigint, string], bigint>;
  'getCommentsForPostAsLocal': ActorMethod<[bigint, bigint], Array<Comment>>;
  'deleteCommentAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'joinVoiceChannel': ActorMethod<[bigint], Array<VoiceParticipant>>;
  'leaveVoiceChannel': ActorMethod<[bigint], undefined>;
  'getVoiceParticipants': ActorMethod<[bigint], Array<VoiceParticipant>>;
  'sendSignal': ActorMethod<[bigint, string, string, string], undefined>;
  'getMySignals': ActorMethod<[bigint], Array<Signal>>;
  'setMicActive': ActorMethod<[bigint, boolean], undefined>;
  'sendCallRequestAsLocal': ActorMethod<[bigint, string], bigint>;
  'getCallRequestsAsLocal': ActorMethod<[bigint], Array<any>>;
  'acceptCallRequestAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'denyCallRequestAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'endCallAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'getNotificationsAsLocal': ActorMethod<[bigint], Array<Notification>>;
  'markNotificationReadAsLocal': ActorMethod<[bigint, bigint], undefined>;
  'markAllNotificationsReadAsLocal': ActorMethod<[bigint], undefined>;
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
