/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CallRequest = IDL.Record({
  'id' : IDL.Nat,
  'timestamp' : Time,
  'callee' : IDL.Principal,
  'caller' : IDL.Principal,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'fname' : IDL.Text,
  'name' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'telephone' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
});
export const User = IDL.Record({
  'fname' : IDL.Text,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
  'photo' : IDL.Opt(ExternalBlob),
  'telephone' : IDL.Text,
});
export const LocalUser = IDL.Record({
  'username': IDL.Text,
  'displayName': IDL.Text,
  'passwordHash': IDL.Text,
  'age': IDL.Nat,
  'photo': IDL.Opt(ExternalBlob),
});
export const Post = IDL.Record({
  'id': IDL.Nat,
  'author': IDL.Principal,
  'authorName': IDL.Text,
  'text': IDL.Text,
  'timestamp': Time,
});
export const Comment = IDL.Record({
  'id': IDL.Nat,
  'postId': IDL.Nat,
  'author': IDL.Principal,
  'authorName': IDL.Text,
  'text': IDL.Text,
  'timestamp': Time,
});
export const VoiceParticipant = IDL.Record({
  'username': IDL.Text,
  'displayName': IDL.Text,
  'isMicActive': IDL.Bool,
});
export const Signal = IDL.Record({
  'id': IDL.Nat,
  'fromUsername': IDL.Text,
  'toUsername': IDL.Text,
  'signalType': IDL.Text,
  'data': IDL.Text,
  'timestamp': Time,
});
export const NotificationType = IDL.Variant({
  'like': IDL.Null,
  'comment': IDL.Null,
  'callRequest': IDL.Null,
});
export const Notification = IDL.Record({
  'id': IDL.Nat,
  'recipientUsername': IDL.Text,
  'notifType': NotificationType,
  'actorName': IDL.Text,
  'postId': IDL.Opt(IDL.Nat),
  'postText': IDL.Opt(IDL.Text),
  'callRequestId': IDL.Opt(IDL.Nat),
  'timestamp': Time,
  'isRead': IDL.Bool,
});
export const LocalCallRequest = IDL.Record({
  'id': IDL.Nat,
  'callerUsername': IDL.Text,
  'calleeUsername': IDL.Text,
  'status': IDL.Variant({ 'pending': IDL.Null, 'accepted': IDL.Null, 'ended': IDL.Null, 'denied': IDL.Null }),
  'timestamp': Time,
});
export const DirectMessage = IDL.Record({
  'id': IDL.Nat,
  'senderUsername': IDL.Text,
  'recipientUsername': IDL.Text,
  'text': IDL.Text,
  'timestamp': Time,
  'isRead': IDL.Bool,
});
export const ConversationSummary = IDL.Record({
  'otherUsername': IDL.Text,
  'otherDisplayName': IDL.Text,
  'lastMessage': IDL.Text,
  'lastTimestamp': Time,
  'unreadCount': IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getCallRequest' : IDL.Func([IDL.Nat], [IDL.Opt(CallRequest)], ['query']),
  'getCallRequests' : IDL.Func([], [IDL.Vec(CallRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'verifyUser' : IDL.Func([], [], []),
  'registerLocalAccount': IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
  'loginLocalAccount': IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'logoutLocalAccount': IDL.Func([IDL.Nat], [], []),
  'validateSessionToken': IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
  'getLocalUserProfile': IDL.Func([IDL.Nat], [IDL.Opt(LocalUser)], ['query']),
  'updateLocalUserPhoto': IDL.Func([IDL.Nat, ExternalBlob], [], []),
  'getLocalUsers': IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
  'sendMessageAsLocal': IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getMessagesAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'sendDirectMessage': IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getDirectMessages': IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(DirectMessage)], ['query']),
  'getConversations': IDL.Func([IDL.Nat], [IDL.Vec(ConversationSummary)], ['query']),
  'markDirectMessagesRead': IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getUnreadDMCount': IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'createPostAsLocal': IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getPostsAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'deletePostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'likePostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'unlikePostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getPostLikesAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
  'addCommentAsLocal': IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getCommentsForPostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'deleteCommentAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'joinVoiceChannel': IDL.Func([IDL.Nat], [IDL.Vec(VoiceParticipant)], []),
  'leaveVoiceChannel': IDL.Func([IDL.Nat], [], []),
  'getVoiceParticipants': IDL.Func([IDL.Nat], [IDL.Vec(VoiceParticipant)], ['query']),
  'sendSignal': IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getMySignals': IDL.Func([IDL.Nat], [IDL.Vec(Signal)], []),
  'setMicActive': IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'sendCallRequestAsLocal': IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'getCallRequestsAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(LocalCallRequest)], ['query']),
  'acceptCallRequestAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'denyCallRequestAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'endCallAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'getNotificationsAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
  'markNotificationReadAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'markAllNotificationsReadAsLocal': IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CallRequest = IDL.Record({
    'id' : IDL.Nat,
    'timestamp' : Time,
    'callee' : IDL.Principal,
    'caller' : IDL.Principal,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'fname' : IDL.Text,
    'name' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'telephone' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const User = IDL.Record({
    'fname' : IDL.Text,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
    'photo' : IDL.Opt(ExternalBlob),
    'telephone' : IDL.Text,
  });
  const LocalUser = IDL.Record({
    'username': IDL.Text,
    'displayName': IDL.Text,
    'passwordHash': IDL.Text,
    'age': IDL.Nat,
    'photo': IDL.Opt(ExternalBlob),
  });
  const Post = IDL.Record({
    'id': IDL.Nat,
    'author': IDL.Principal,
    'authorName': IDL.Text,
    'text': IDL.Text,
    'timestamp': Time,
  });
  const Comment = IDL.Record({
    'id': IDL.Nat,
    'postId': IDL.Nat,
    'author': IDL.Principal,
    'authorName': IDL.Text,
    'text': IDL.Text,
    'timestamp': Time,
  });
  const VoiceParticipant = IDL.Record({
    'username': IDL.Text,
    'displayName': IDL.Text,
    'isMicActive': IDL.Bool,
  });
  const Signal = IDL.Record({
    'id': IDL.Nat,
    'fromUsername': IDL.Text,
    'toUsername': IDL.Text,
    'signalType': IDL.Text,
    'data': IDL.Text,
    'timestamp': Time,
  });
  const NotificationType = IDL.Variant({
    'like': IDL.Null,
    'comment': IDL.Null,
    'callRequest': IDL.Null,
  });
  const Notification = IDL.Record({
    'id': IDL.Nat,
    'recipientUsername': IDL.Text,
    'notifType': NotificationType,
    'actorName': IDL.Text,
    'postId': IDL.Opt(IDL.Nat),
    'postText': IDL.Opt(IDL.Text),
    'callRequestId': IDL.Opt(IDL.Nat),
    'timestamp': Time,
    'isRead': IDL.Bool,
  });
  const LocalCallRequest = IDL.Record({
    'id': IDL.Nat,
    'callerUsername': IDL.Text,
    'calleeUsername': IDL.Text,
    'status': IDL.Variant({ 'pending': IDL.Null, 'accepted': IDL.Null, 'ended': IDL.Null, 'denied': IDL.Null }),
    'timestamp': Time,
  });
  const DirectMessage = IDL.Record({
    'id': IDL.Nat,
    'senderUsername': IDL.Text,
    'recipientUsername': IDL.Text,
    'text': IDL.Text,
    'timestamp': Time,
    'isRead': IDL.Bool,
  });
  const ConversationSummary = IDL.Record({
    'otherUsername': IDL.Text,
    'otherDisplayName': IDL.Text,
    'lastMessage': IDL.Text,
    'lastTimestamp': Time,
    'unreadCount': IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getCallRequest' : IDL.Func([IDL.Nat], [IDL.Opt(CallRequest)], ['query']),
    'getCallRequests' : IDL.Func([], [IDL.Vec(CallRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessage' : IDL.Func([IDL.Nat], [IDL.Opt(Message)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getUsersCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'verifyUser' : IDL.Func([], [], []),
    'registerLocalAccount': IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(ExternalBlob)], [], []),
    'loginLocalAccount': IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'logoutLocalAccount': IDL.Func([IDL.Nat], [], []),
    'validateSessionToken': IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], ['query']),
    'getLocalUserProfile': IDL.Func([IDL.Nat], [IDL.Opt(LocalUser)], ['query']),
    'updateLocalUserPhoto': IDL.Func([IDL.Nat, ExternalBlob], [], []),
    'getLocalUsers': IDL.Func([], [IDL.Vec(LocalUser)], ['query']),
    'sendMessageAsLocal': IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getMessagesAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'sendDirectMessage': IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getDirectMessages': IDL.Func([IDL.Nat, IDL.Text], [IDL.Vec(DirectMessage)], ['query']),
    'getConversations': IDL.Func([IDL.Nat], [IDL.Vec(ConversationSummary)], ['query']),
    'markDirectMessagesRead': IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getUnreadDMCount': IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'createPostAsLocal': IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getPostsAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'deletePostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'likePostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'unlikePostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getPostLikesAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(IDL.Text)], ['query']),
    'addCommentAsLocal': IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getCommentsForPostAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'deleteCommentAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'joinVoiceChannel': IDL.Func([IDL.Nat], [IDL.Vec(VoiceParticipant)], []),
    'leaveVoiceChannel': IDL.Func([IDL.Nat], [], []),
    'getVoiceParticipants': IDL.Func([IDL.Nat], [IDL.Vec(VoiceParticipant)], ['query']),
    'sendSignal': IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getMySignals': IDL.Func([IDL.Nat], [IDL.Vec(Signal)], []),
    'setMicActive': IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'sendCallRequestAsLocal': IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'getCallRequestsAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(LocalCallRequest)], ['query']),
    'acceptCallRequestAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'denyCallRequestAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'endCallAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'getNotificationsAsLocal': IDL.Func([IDL.Nat], [IDL.Vec(Notification)], ['query']),
    'markNotificationReadAsLocal': IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'markAllNotificationsReadAsLocal': IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
