/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Signal {
    id: bigint;
    data: string;
    toUsername: string;
    timestamp: Time;
    fromUsername: string;
    signalType: string;
}
export interface VoiceParticipant {
    username: string;
    displayName: string;
    isMicActive: boolean;
}
export type Time = bigint;
export interface Comment {
    id: bigint;
    text: string;
    authorName: string;
    author: Principal;
    timestamp: Time;
    postId: bigint;
}
export interface User {
    fname: string;
    principal: Principal;
    name: string;
    role: UserRole;
    photo?: ExternalBlob;
    telephone: string;
}
export interface LocalCallRequest {
    id: bigint;
    status: CallStatus;
    callerUsername: string;
    timestamp: Time;
    calleeUsername: string;
}
export interface MessageReaction {
    emoji: string;
    timestamp: Time;
    reactorUsername: string;
}
export interface LocalUser {
    age: bigint;
    username: string;
    displayName: string;
    lastNameChange?: Time;
    passwordHash: string;
    photo?: ExternalBlob;
}
export interface CallRequestWithStatus {
    id: bigint;
    status: CallStatus;
    timestamp: Time;
    callee: Principal;
    caller: Principal;
}
export interface Post {
    id: bigint;
    text: string;
    authorName: string;
    author: Principal;
    timestamp: Time;
}
export type SessionToken = bigint;
export interface Notification {
    id: bigint;
    postText?: string;
    callRequestId?: bigint;
    actorName: string;
    notifType: NotificationType;
    isRead: boolean;
    timestamp: Time;
    recipientUsername: string;
    postId?: bigint;
}
export interface Message {
    id: bigint;
    text: string;
    authorName: string;
    author: Principal;
    timestamp: Time;
}
export interface AdminUserInfo {
    username: string;
    displayName: string;
    banExpiresAt?: Time;
    email?: string;
    isVerified: boolean;
    isBanned: boolean;
}
export interface ProfileSettings {
    hideFollowers: boolean;
    hideFollowing: boolean;
}
export interface ConversationSummary {
    lastMessageIsRead: boolean;
    lastMessageSender: string;
    otherUsername: string;
    lastMessage: string;
    unreadCount: bigint;
    lastTimestamp: Time;
    otherDisplayName: string;
}
export interface UserProfile {
    fname: string;
    name: string;
    photo?: ExternalBlob;
    telephone: string;
}
export interface DirectMessage {
    id: bigint;
    text: string;
    senderUsername: string;
    isRead: boolean;
    timestamp: Time;
    recipientUsername: string;
}
export enum CallStatus {
    pending = "pending",
    denied = "denied",
    ended = "ended",
    accepted = "accepted"
}
export enum NotificationType {
    like = "like",
    comment = "comment",
    callRequest = "callRequest"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    acceptCallRequest(id: bigint): Promise<void>;
    acceptCallRequestAsLocal(token: SessionToken, id: bigint): Promise<void>;
    addComment(postId: bigint, text: string): Promise<bigint>;
    addCommentAsLocal(token: SessionToken, postId: bigint, text: string): Promise<bigint>;
    addMessageReaction(token: SessionToken, msgId: bigint, emoji: string): Promise<void>;
    assignRole(user: Principal, role: UserRole): Promise<void>;
    banLocalUser(token: SessionToken, targetUsername: string): Promise<void>;
    banLocalUserWithDuration(token: SessionToken, targetUsername: string, durationNs: bigint): Promise<void>;
    blockUser(token: SessionToken, targetUsername: string): Promise<void>;
    checkIsWildfireAdmin(token: SessionToken): Promise<boolean>;
    clearCallTopic(token: SessionToken): Promise<void>;
    createPost(text: string): Promise<bigint>;
    createPostAsLocal(token: SessionToken, text: string): Promise<bigint>;
    createUser(name: string, fname: string, telephone: string): Promise<void>;
    deleteCallRequest(id: bigint): Promise<void>;
    deleteComment(id: bigint): Promise<void>;
    deleteCommentAsLocal(token: SessionToken, id: bigint): Promise<void>;
    deleteDirectMessage(token: SessionToken, msgId: bigint): Promise<void>;
    deletePost(id: bigint): Promise<void>;
    deletePostAsLocal(token: SessionToken, id: bigint): Promise<void>;
    deleteUser(targetUser: Principal): Promise<void>;
    denyCallRequest(id: bigint): Promise<void>;
    denyCallRequestAsLocal(token: SessionToken, id: bigint): Promise<void>;
    endCall(id: bigint): Promise<void>;
    endCallAsLocal(token: SessionToken, id: bigint): Promise<void>;
    followUser(token: SessionToken, targetUsername: string): Promise<void>;
    getAllUsersForAdmin(token: SessionToken): Promise<Array<AdminUserInfo>>;
    getBanExpiry(username: string): Promise<Time | null>;
    getBlockedUsers(token: SessionToken): Promise<Array<string>>;
    getCallRequest(id: bigint): Promise<CallRequestWithStatus | null>;
    getCallRequests(): Promise<Array<CallRequestWithStatus>>;
    getCallRequestsAsLocal(token: SessionToken): Promise<Array<LocalCallRequest>>;
    getCallTopic(username: string): Promise<string | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCommentsForPost(postId: bigint): Promise<Array<Comment>>;
    getCommentsForPostAsLocal(token: SessionToken, postId: bigint): Promise<Array<Comment>>;
    getConversations(token: SessionToken): Promise<Array<ConversationSummary>>;
    getDirectMessages(token: SessionToken, otherUsername: string): Promise<Array<DirectMessage>>;
    getFollowers(token: SessionToken, username: string): Promise<Array<string>>;
    getFollowing(token: SessionToken, username: string): Promise<Array<string>>;
    getLocalUserProfile(token: SessionToken): Promise<LocalUser | null>;
    getLocalUsers(): Promise<Array<LocalUser>>;
    getMessage(id: bigint): Promise<Message | null>;
    getMessageReactions(token: SessionToken, msgId: bigint): Promise<Array<MessageReaction>>;
    getMessages(): Promise<Array<Message>>;
    getMessagesAsLocal(token: SessionToken): Promise<Array<Message>>;
    getMySignals(token: SessionToken): Promise<Array<Signal>>;
    getNotificationsAsLocal(token: SessionToken): Promise<Array<Notification>>;
    getOnlineUsernames(): Promise<Array<string>>;
    getPinnedMessage(token: SessionToken, otherUsername: string): Promise<DirectMessage | null>;
    getPostLikes(postId: bigint): Promise<Array<string>>;
    getPostLikesAsLocal(token: SessionToken, postId: bigint): Promise<Array<string>>;
    getPosts(): Promise<Array<Post>>;
    getPostsAsLocal(token: SessionToken): Promise<Array<Post>>;
    getProfileSettings(token: SessionToken): Promise<ProfileSettings>;
    getProfileVisitors(token: SessionToken, username: string): Promise<{
        visitors: Array<string>;
        count: bigint;
    }>;
    getProfileWithSocial(token: SessionToken, targetUsername: string): Promise<{
        isVerified: boolean;
        isFollowing: boolean;
        followerCount: bigint;
        followingCount: bigint;
        profile?: LocalUser;
    }>;
    getPublicProfileSettings(username: string): Promise<ProfileSettings>;
    getReshareCount(postId: bigint): Promise<bigint>;
    getTypingStatus(token: SessionToken, otherUsername: string): Promise<boolean>;
    getUnreadDMCount(token: SessionToken): Promise<bigint>;
    getUser(principal: Principal): Promise<User | null>;
    getUserBadges(username: string): Promise<Array<string>>;
    getUserBio(username: string): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserStatus(username: string): Promise<string | null>;
    getUsers(): Promise<Array<User>>;
    getUsersCount(): Promise<bigint>;
    getUsersForMatching(token: SessionToken): Promise<Array<LocalUser>>;
    getVoiceParticipants(token: SessionToken): Promise<Array<VoiceParticipant>>;
    grantVerifiedBadge(token: SessionToken, targetUsername: string): Promise<void>;
    isBlocked(token: SessionToken, targetUsername: string): Promise<boolean>;
    isBlockedBy(token: SessionToken, targetUsername: string): Promise<boolean>;
    isFollowing(token: SessionToken, targetUsername: string): Promise<boolean>;
    isUserBanned(username: string): Promise<boolean>;
    isUserVerified(username: string): Promise<boolean>;
    joinVoiceChannel(token: SessionToken): Promise<Array<VoiceParticipant>>;
    leaveVoiceChannel(token: SessionToken): Promise<void>;
    likePost(postId: bigint): Promise<void>;
    likePostAsLocal(token: SessionToken, postId: bigint): Promise<void>;
    loginLocalAccount(username: string, passwordHash: string): Promise<{
        token: SessionToken;
        isAdmin: boolean;
    }>;
    logoutLocalAccount(token: SessionToken): Promise<void>;
    markAllNotificationsReadAsLocal(token: SessionToken): Promise<void>;
    markDirectMessagesRead(token: SessionToken, otherUsername: string): Promise<void>;
    markNotificationReadAsLocal(token: SessionToken, id: bigint): Promise<void>;
    pinDirectMessage(token: SessionToken, otherUsername: string, msgId: bigint): Promise<void>;
    pingOnline(token: SessionToken): Promise<void>;
    recordProfileVisit(token: SessionToken, visitedUsername: string): Promise<void>;
    registerLocalAccount(username: string, passwordHash: string, displayName: string, age: bigint, photo: ExternalBlob | null): Promise<void>;
    removeMessageReaction(token: SessionToken, msgId: bigint, emoji: string): Promise<void>;
    resetPasswordAsAdmin(token: SessionToken, targetUsername: string, newPasswordHash: string): Promise<void>;
    resharePost(token: SessionToken, originalPostId: bigint): Promise<bigint>;
    revokeVerifiedBadge(token: SessionToken, targetUsername: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendCallRequest(callee: Principal): Promise<bigint>;
    sendCallRequestAsLocal(token: SessionToken, calleeUsername: string): Promise<bigint>;
    sendDirectMessage(token: SessionToken, recipientUsername: string, text: string): Promise<bigint>;
    sendMessage(text: string): Promise<bigint>;
    sendMessageAsLocal(token: SessionToken, text: string): Promise<bigint>;
    sendSignal(token: SessionToken, toUsername: string, signalType: string, data: string): Promise<void>;
    setCallTopic(token: SessionToken, topic: string): Promise<void>;
    setMicActive(token: SessionToken, active: boolean): Promise<void>;
    setTypingStatus(token: SessionToken, otherUsername: string, isTyping: boolean): Promise<void>;
    setUserEmail(token: SessionToken, email: string): Promise<void>;
    setUserStatus(token: SessionToken, status: string): Promise<void>;
    trackCallActivity(token: SessionToken): Promise<void>;
    unbanLocalUser(token: SessionToken, targetUsername: string): Promise<void>;
    unblockUser(token: SessionToken, targetUsername: string): Promise<void>;
    unfollowUser(token: SessionToken, targetUsername: string): Promise<void>;
    unlikePost(postId: bigint): Promise<void>;
    unlikePostAsLocal(token: SessionToken, postId: bigint): Promise<void>;
    updateLocalUserBio(token: SessionToken, bio: string): Promise<void>;
    updateLocalUserDisplayName(token: SessionToken, newDisplayName: string): Promise<string>;
    updateLocalUserPhoto(token: SessionToken, photo: ExternalBlob): Promise<void>;
    updateProfileSettings(token: SessionToken, hideFollowers: boolean, hideFollowing: boolean): Promise<void>;
    updateUser(photo: ExternalBlob): Promise<void>;
    updateUserWithoutPhoto(name: string, fname: string, telephone: string): Promise<void>;
    validateSessionToken(token: SessionToken): Promise<string | null>;
    verifyUser(): Promise<void>;
}
import type { AdminUserInfo as _AdminUserInfo, CallRequestWithStatus as _CallRequestWithStatus, CallStatus as _CallStatus, DirectMessage as _DirectMessage, ExternalBlob as _ExternalBlob, LocalCallRequest as _LocalCallRequest, LocalUser as _LocalUser, Message as _Message, Notification as _Notification, NotificationType as _NotificationType, Time as _Time, User as _User, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptCallRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptCallRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptCallRequest(arg0);
            return result;
        }
    }
    async acceptCallRequestAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptCallRequestAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptCallRequestAsLocal(arg0, arg1);
            return result;
        }
    }
    async addComment(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return result;
        }
    }
    async addCommentAsLocal(arg0: SessionToken, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addCommentAsLocal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCommentAsLocal(arg0, arg1, arg2);
            return result;
        }
    }
    async addMessageReaction(arg0: SessionToken, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessageReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessageReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banLocalUser(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banLocalUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banLocalUser(arg0, arg1);
            return result;
        }
    }
    async banLocalUserWithDuration(arg0: SessionToken, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banLocalUserWithDuration(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banLocalUserWithDuration(arg0, arg1, arg2);
            return result;
        }
    }
    async blockUser(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockUser(arg0, arg1);
            return result;
        }
    }
    async checkIsWildfireAdmin(arg0: SessionToken): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIsWildfireAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIsWildfireAdmin(arg0);
            return result;
        }
    }
    async clearCallTopic(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCallTopic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCallTopic(arg0);
            return result;
        }
    }
    async createPost(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(arg0);
            return result;
        }
    }
    async createPostAsLocal(arg0: SessionToken, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPostAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPostAsLocal(arg0, arg1);
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCallRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCallRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCallRequest(arg0);
            return result;
        }
    }
    async deleteComment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteCommentAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCommentAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCommentAsLocal(arg0, arg1);
            return result;
        }
    }
    async deleteDirectMessage(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDirectMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDirectMessage(arg0, arg1);
            return result;
        }
    }
    async deletePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deletePostAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePostAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePostAsLocal(arg0, arg1);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async denyCallRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyCallRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyCallRequest(arg0);
            return result;
        }
    }
    async denyCallRequestAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyCallRequestAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyCallRequestAsLocal(arg0, arg1);
            return result;
        }
    }
    async endCall(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endCall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endCall(arg0);
            return result;
        }
    }
    async endCallAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.endCallAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endCallAsLocal(arg0, arg1);
            return result;
        }
    }
    async followUser(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followUser(arg0, arg1);
            return result;
        }
    }
    async getAllUsersForAdmin(arg0: SessionToken): Promise<Array<AdminUserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersForAdmin(arg0);
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersForAdmin(arg0);
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBanExpiry(arg0: string): Promise<Time | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBanExpiry(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBanExpiry(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlockedUsers(arg0: SessionToken): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlockedUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlockedUsers(arg0);
            return result;
        }
    }
    async getCallRequest(arg0: bigint): Promise<CallRequestWithStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallRequest(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallRequest(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallRequests(): Promise<Array<CallRequestWithStatus>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallRequests();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallRequests();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallRequestsAsLocal(arg0: SessionToken): Promise<Array<LocalCallRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallRequestsAsLocal(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallRequestsAsLocal(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallTopic(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallTopic(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallTopic(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommentsForPost(arg0: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsForPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsForPost(arg0);
            return result;
        }
    }
    async getCommentsForPostAsLocal(arg0: SessionToken, arg1: bigint): Promise<Array<Comment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommentsForPostAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommentsForPostAsLocal(arg0, arg1);
            return result;
        }
    }
    async getConversations(arg0: SessionToken): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations(arg0);
            return result;
        }
    }
    async getDirectMessages(arg0: SessionToken, arg1: string): Promise<Array<DirectMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectMessages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectMessages(arg0, arg1);
            return result;
        }
    }
    async getFollowers(arg0: SessionToken, arg1: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowers(arg0, arg1);
            return result;
        }
    }
    async getFollowing(arg0: SessionToken, arg1: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFollowing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFollowing(arg0, arg1);
            return result;
        }
    }
    async getLocalUserProfile(arg0: SessionToken): Promise<LocalUser | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLocalUsers(): Promise<Array<LocalUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLocalUsers();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLocalUsers();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessage(arg0: bigint): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessage(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessage(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessageReactions(arg0: SessionToken, arg1: bigint): Promise<Array<MessageReaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessageReactions(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessageReactions(arg0, arg1);
            return result;
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getMessagesAsLocal(arg0: SessionToken): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesAsLocal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesAsLocal(arg0);
            return result;
        }
    }
    async getMySignals(arg0: SessionToken): Promise<Array<Signal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySignals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySignals(arg0);
            return result;
        }
    }
    async getNotificationsAsLocal(arg0: SessionToken): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsAsLocal(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsAsLocal(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOnlineUsernames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOnlineUsernames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOnlineUsernames();
            return result;
        }
    }
    async getPinnedMessage(arg0: SessionToken, arg1: string): Promise<DirectMessage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPinnedMessage(arg0, arg1);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPinnedMessage(arg0, arg1);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostLikes(arg0: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostLikes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostLikes(arg0);
            return result;
        }
    }
    async getPostLikesAsLocal(arg0: SessionToken, arg1: bigint): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostLikesAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostLikesAsLocal(arg0, arg1);
            return result;
        }
    }
    async getPosts(): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPosts();
            return result;
        }
    }
    async getPostsAsLocal(arg0: SessionToken): Promise<Array<Post>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsAsLocal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsAsLocal(arg0);
            return result;
        }
    }
    async getProfileSettings(arg0: SessionToken): Promise<ProfileSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileSettings(arg0);
            return result;
        }
    }
    async getProfileVisitors(arg0: SessionToken, arg1: string): Promise<{
        visitors: Array<string>;
        count: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileVisitors(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileVisitors(arg0, arg1);
            return result;
        }
    }
    async getProfileWithSocial(arg0: SessionToken, arg1: string): Promise<{
        isVerified: boolean;
        isFollowing: boolean;
        followerCount: bigint;
        followingCount: bigint;
        profile?: LocalUser;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileWithSocial(arg0, arg1);
                return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileWithSocial(arg0, arg1);
            return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicProfileSettings(arg0: string): Promise<ProfileSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicProfileSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicProfileSettings(arg0);
            return result;
        }
    }
    async getReshareCount(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReshareCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReshareCount(arg0);
            return result;
        }
    }
    async getTypingStatus(arg0: SessionToken, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getTypingStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTypingStatus(arg0, arg1);
            return result;
        }
    }
    async getUnreadDMCount(arg0: SessionToken): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadDMCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadDMCount(arg0);
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBadges(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBadges(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBadges(arg0);
            return result;
        }
    }
    async getUserBio(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBio(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBio(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserStatus(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserStatus(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserStatus(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsersCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersCount();
            return result;
        }
    }
    async getUsersForMatching(arg0: SessionToken): Promise<Array<LocalUser>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersForMatching(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersForMatching(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVoiceParticipants(arg0: SessionToken): Promise<Array<VoiceParticipant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVoiceParticipants(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVoiceParticipants(arg0);
            return result;
        }
    }
    async grantVerifiedBadge(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantVerifiedBadge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantVerifiedBadge(arg0, arg1);
            return result;
        }
    }
    async isBlocked(arg0: SessionToken, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBlocked(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBlocked(arg0, arg1);
            return result;
        }
    }
    async isBlockedBy(arg0: SessionToken, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isBlockedBy(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isBlockedBy(arg0, arg1);
            return result;
        }
    }
    async isFollowing(arg0: SessionToken, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isFollowing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isFollowing(arg0, arg1);
            return result;
        }
    }
    async isUserBanned(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserBanned(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserBanned(arg0);
            return result;
        }
    }
    async isUserVerified(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserVerified(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserVerified(arg0);
            return result;
        }
    }
    async joinVoiceChannel(arg0: SessionToken): Promise<Array<VoiceParticipant>> {
        if (this.processError) {
            try {
                const result = await this.actor.joinVoiceChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinVoiceChannel(arg0);
            return result;
        }
    }
    async leaveVoiceChannel(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveVoiceChannel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveVoiceChannel(arg0);
            return result;
        }
    }
    async likePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likePostAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.likePostAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePostAsLocal(arg0, arg1);
            return result;
        }
    }
    async loginLocalAccount(arg0: string, arg1: string): Promise<{
        token: SessionToken;
        isAdmin: boolean;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginLocalAccount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginLocalAccount(arg0, arg1);
            return result;
        }
    }
    async logoutLocalAccount(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logoutLocalAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logoutLocalAccount(arg0);
            return result;
        }
    }
    async markAllNotificationsReadAsLocal(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsReadAsLocal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsReadAsLocal(arg0);
            return result;
        }
    }
    async markDirectMessagesRead(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markDirectMessagesRead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markDirectMessagesRead(arg0, arg1);
            return result;
        }
    }
    async markNotificationReadAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationReadAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationReadAsLocal(arg0, arg1);
            return result;
        }
    }
    async pinDirectMessage(arg0: SessionToken, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pinDirectMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pinDirectMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async pingOnline(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.pingOnline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.pingOnline(arg0);
            return result;
        }
    }
    async recordProfileVisit(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordProfileVisit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordProfileVisit(arg0, arg1);
            return result;
        }
    }
    async registerLocalAccount(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerLocalAccount(arg0, arg1, arg2, arg3, await to_candid_opt_n41(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerLocalAccount(arg0, arg1, arg2, arg3, await to_candid_opt_n41(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async removeMessageReaction(arg0: SessionToken, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMessageReaction(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMessageReaction(arg0, arg1, arg2);
            return result;
        }
    }
    async resetPasswordAsAdmin(arg0: SessionToken, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPasswordAsAdmin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPasswordAsAdmin(arg0, arg1, arg2);
            return result;
        }
    }
    async resharePost(arg0: SessionToken, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.resharePost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resharePost(arg0, arg1);
            return result;
        }
    }
    async revokeVerifiedBadge(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeVerifiedBadge(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeVerifiedBadge(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n43(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async sendCallRequest(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCallRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCallRequest(arg0);
            return result;
        }
    }
    async sendCallRequestAsLocal(arg0: SessionToken, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendCallRequestAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendCallRequestAsLocal(arg0, arg1);
            return result;
        }
    }
    async sendDirectMessage(arg0: SessionToken, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendDirectMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendDirectMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async sendMessage(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0);
            return result;
        }
    }
    async sendMessageAsLocal(arg0: SessionToken, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessageAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessageAsLocal(arg0, arg1);
            return result;
        }
    }
    async sendSignal(arg0: SessionToken, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendSignal(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendSignal(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setCallTopic(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCallTopic(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCallTopic(arg0, arg1);
            return result;
        }
    }
    async setMicActive(arg0: SessionToken, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setMicActive(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setMicActive(arg0, arg1);
            return result;
        }
    }
    async setTypingStatus(arg0: SessionToken, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTypingStatus(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTypingStatus(arg0, arg1, arg2);
            return result;
        }
    }
    async setUserEmail(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserEmail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserEmail(arg0, arg1);
            return result;
        }
    }
    async setUserStatus(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserStatus(arg0, arg1);
            return result;
        }
    }
    async trackCallActivity(arg0: SessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.trackCallActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackCallActivity(arg0);
            return result;
        }
    }
    async unbanLocalUser(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanLocalUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanLocalUser(arg0, arg1);
            return result;
        }
    }
    async unblockUser(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockUser(arg0, arg1);
            return result;
        }
    }
    async unfollowUser(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowUser(arg0, arg1);
            return result;
        }
    }
    async unlikePost(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePost(arg0);
            return result;
        }
    }
    async unlikePostAsLocal(arg0: SessionToken, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unlikePostAsLocal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unlikePostAsLocal(arg0, arg1);
            return result;
        }
    }
    async updateLocalUserBio(arg0: SessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocalUserBio(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocalUserBio(arg0, arg1);
            return result;
        }
    }
    async updateLocalUserDisplayName(arg0: SessionToken, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocalUserDisplayName(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocalUserDisplayName(arg0, arg1);
            return result;
        }
    }
    async updateLocalUserPhoto(arg0: SessionToken, arg1: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocalUserPhoto(arg0, await to_candid_ExternalBlob_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocalUserPhoto(arg0, await to_candid_ExternalBlob_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfileSettings(arg0: SessionToken, arg1: boolean, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileSettings(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileSettings(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUser(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(await to_candid_ExternalBlob_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(await to_candid_ExternalBlob_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateUserWithoutPhoto(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserWithoutPhoto(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserWithoutPhoto(arg0, arg1, arg2);
            return result;
        }
    }
    async validateSessionToken(arg0: SessionToken): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSessionToken(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSessionToken(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUser();
            return result;
        }
    }
}
function from_candid_AdminUserInfo_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminUserInfo): AdminUserInfo {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_CallRequestWithStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallRequestWithStatus): CallRequestWithStatus {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CallStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CallStatus): CallStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LocalCallRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocalCallRequest): LocalCallRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_LocalUser_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LocalUser): Promise<LocalUser> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
async function from_candid_User_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): Promise<User> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n21(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LocalUser]): Promise<LocalUser | null> {
    return value.length === 0 ? null : await from_candid_LocalUser_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DirectMessage]): DirectMessage | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): Promise<User | null> {
    return value.length === 0 ? null : await from_candid_User_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallRequestWithStatus]): CallRequestWithStatus | null {
    return value.length === 0 ? null : from_candid_CallRequestWithStatus_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CallStatus;
    timestamp: _Time;
    callee: Principal;
    caller: Principal;
}): {
    id: bigint;
    status: CallStatus;
    timestamp: Time;
    callee: Principal;
    caller: Principal;
} {
    return {
        id: value.id,
        status: from_candid_CallStatus_n11(_uploadFile, _downloadFile, value.status),
        timestamp: value.timestamp,
        callee: value.callee,
        caller: value.caller
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CallStatus;
    callerUsername: string;
    timestamp: _Time;
    calleeUsername: string;
}): {
    id: bigint;
    status: CallStatus;
    callerUsername: string;
    timestamp: Time;
    calleeUsername: string;
} {
    return {
        id: value.id,
        status: from_candid_CallStatus_n11(_uploadFile, _downloadFile, value.status),
        callerUsername: value.callerUsername,
        timestamp: value.timestamp,
        calleeUsername: value.calleeUsername
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fname: string;
    name: string;
    photo: [] | [_ExternalBlob];
    telephone: string;
}): Promise<{
    fname: string;
    name: string;
    photo?: ExternalBlob;
    telephone: string;
}> {
    return {
        fname: value.fname,
        name: value.name,
        photo: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.photo)),
        telephone: value.telephone
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    username: string;
    displayName: string;
    lastNameChange: [] | [_Time];
    passwordHash: string;
    photo: [] | [_ExternalBlob];
}): Promise<{
    age: bigint;
    username: string;
    displayName: string;
    lastNameChange?: Time;
    passwordHash: string;
    photo?: ExternalBlob;
}> {
    return {
        age: value.age,
        username: value.username,
        displayName: value.displayName,
        lastNameChange: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.lastNameChange)),
        passwordHash: value.passwordHash,
        photo: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    postText: [] | [string];
    callRequestId: [] | [bigint];
    actorName: string;
    notifType: _NotificationType;
    isRead: boolean;
    timestamp: _Time;
    recipientUsername: string;
    postId: [] | [bigint];
}): {
    id: bigint;
    postText?: string;
    callRequestId?: bigint;
    actorName: string;
    notifType: NotificationType;
    isRead: boolean;
    timestamp: Time;
    recipientUsername: string;
    postId?: bigint;
} {
    return {
        id: value.id,
        postText: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.postText)),
        callRequestId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.callRequestId)),
        actorName: value.actorName,
        notifType: from_candid_NotificationType_n31(_uploadFile, _downloadFile, value.notifType),
        isRead: value.isRead,
        timestamp: value.timestamp,
        recipientUsername: value.recipientUsername,
        postId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.postId))
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isVerified: boolean;
    isFollowing: boolean;
    followerCount: bigint;
    followingCount: bigint;
    profile: [] | [_LocalUser];
}): Promise<{
    isVerified: boolean;
    isFollowing: boolean;
    followerCount: bigint;
    followingCount: bigint;
    profile?: LocalUser;
}> {
    return {
        isVerified: value.isVerified,
        isFollowing: value.isFollowing,
        followerCount: value.followerCount,
        followingCount: value.followingCount,
        profile: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.profile))
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fname: string;
    principal: Principal;
    name: string;
    role: _UserRole;
    photo: [] | [_ExternalBlob];
    telephone: string;
}): Promise<{
    fname: string;
    principal: Principal;
    name: string;
    role: UserRole;
    photo?: ExternalBlob;
    telephone: string;
}> {
    return {
        fname: value.fname,
        principal: value.principal,
        name: value.name,
        role: from_candid_UserRole_n38(_uploadFile, _downloadFile, value.role),
        photo: record_opt_to_undefined(await from_candid_opt_n20(_uploadFile, _downloadFile, value.photo)),
        telephone: value.telephone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    banExpiresAt: [] | [_Time];
    email: [] | [string];
    isVerified: boolean;
    isBanned: boolean;
}): {
    username: string;
    displayName: string;
    banExpiresAt?: Time;
    email?: string;
    isVerified: boolean;
    isBanned: boolean;
} {
    return {
        username: value.username,
        displayName: value.displayName,
        banExpiresAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.banExpiresAt)),
        email: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.email)),
        isVerified: value.isVerified,
        isBanned: value.isBanned
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    ended: null;
} | {
    accepted: null;
}): CallStatus {
    return "pending" in value ? CallStatus.pending : "denied" in value ? CallStatus.denied : "ended" in value ? CallStatus.ended : "accepted" in value ? CallStatus.accepted : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like: null;
} | {
    comment: null;
} | {
    callRequest: null;
}): NotificationType {
    return "like" in value ? NotificationType.like : "comment" in value ? NotificationType.comment : "callRequest" in value ? NotificationType.callRequest : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CallRequestWithStatus>): Array<CallRequestWithStatus> {
    return value.map((x)=>from_candid_CallRequestWithStatus_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LocalCallRequest>): Array<LocalCallRequest> {
    return value.map((x)=>from_candid_LocalCallRequest_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LocalUser>): Promise<Array<LocalUser>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LocalUser_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdminUserInfo>): Array<AdminUserInfo> {
    return value.map((x)=>from_candid_AdminUserInfo_n4(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Promise<Array<User>> {
    return await Promise.all(value.map(async (x)=>await from_candid_User_n36(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
async function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n42(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fname: string;
    name: string;
    photo?: ExternalBlob;
    telephone: string;
}): Promise<{
    fname: string;
    name: string;
    photo: [] | [_ExternalBlob];
    telephone: string;
}> {
    return {
        fname: value.fname,
        name: value.name,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n42(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        telephone: value.telephone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
