/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CallRequest {
    id: bigint;
    timestamp: Time;
    callee: Principal;
    caller: Principal;
}
export type Time = bigint;
export interface User {
    fname: string;
    principal: Principal;
    name: string;
    role: UserRole;
    photo?: ExternalBlob;
    telephone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Message {
    id: bigint;
    text: string;
    authorName: string;
    author: Principal;
    timestamp: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserProfile {
    fname: string;
    name: string;
    photo?: ExternalBlob;
    telephone: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface LocalUser {
    username: string;
    displayName: string;
    passwordHash: string;
    age: bigint;
    photo?: ExternalBlob;
}
export interface Post {
    id: bigint;
    author: any;
    authorName: string;
    text: string;
    timestamp: Time;
}
export interface Comment {
    id: bigint;
    postId: bigint;
    author: any;
    authorName: string;
    text: string;
    timestamp: Time;
}
export interface VoiceParticipant {
    username: string;
    displayName: string;
    isMicActive: boolean;
}
export interface Signal {
    id: bigint;
    fromUsername: string;
    toUsername: string;
    signalType: string;
    data: string;
    timestamp: Time;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createUser(name: string, fname: string, telephone: string): Promise<void>;
    deleteUser(targetUser: Principal): Promise<void>;
    getCallRequest(id: bigint): Promise<CallRequest | null>;
    getCallRequests(): Promise<Array<CallRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMessage(id: bigint): Promise<Message | null>;
    getMessages(): Promise<Array<Message>>;
    getUser(principal: Principal): Promise<User | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(): Promise<Array<User>>;
    getUsersCount(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    verifyUser(): Promise<void>;
    registerLocalAccount(username: string, passwordHash: string, displayName: string, age: bigint, photo: ExternalBlob | null): Promise<void>;
    loginLocalAccount(username: string, passwordHash: string): Promise<bigint>;
    logoutLocalAccount(token: bigint): Promise<void>;
    validateSessionToken(token: bigint): Promise<string | null>;
    getLocalUserProfile(token: bigint): Promise<LocalUser | null>;
    updateLocalUserPhoto(token: bigint, photo: ExternalBlob): Promise<void>;
    getLocalUsers(): Promise<Array<LocalUser>>;
    sendDirectMessage(token: bigint, recipientUsername: string, text: string): Promise<bigint>;
    getDirectMessages(token: bigint, otherUsername: string): Promise<Array<any>>;
    getConversations(token: bigint): Promise<Array<any>>;
    markDirectMessagesRead(token: bigint, otherUsername: string): Promise<void>;
    getUnreadDMCount(token: bigint): Promise<bigint>;
    sendMessageAsLocal(token: bigint, text: string): Promise<bigint>;
    getMessagesAsLocal(token: bigint): Promise<Array<Message>>;
    createPostAsLocal(token: bigint, text: string): Promise<bigint>;
    getPostsAsLocal(token: bigint): Promise<Array<Post>>;
    deletePostAsLocal(token: bigint, id: bigint): Promise<void>;
    likePostAsLocal(token: bigint, postId: bigint): Promise<void>;
    unlikePostAsLocal(token: bigint, postId: bigint): Promise<void>;
    getPostLikesAsLocal(token: bigint, postId: bigint): Promise<Array<string>>;
    addCommentAsLocal(token: bigint, postId: bigint, text: string): Promise<bigint>;
    getCommentsForPostAsLocal(token: bigint, postId: bigint): Promise<Array<Comment>>;
    deleteCommentAsLocal(token: bigint, id: bigint): Promise<void>;
    joinVoiceChannel(token: bigint): Promise<Array<VoiceParticipant>>;
    leaveVoiceChannel(token: bigint): Promise<void>;
    getVoiceParticipants(token: bigint): Promise<Array<VoiceParticipant>>;
    sendSignal(token: bigint, toUsername: string, signalType: string, data: string): Promise<void>;
    getMySignals(token: bigint): Promise<Array<Signal>>;
    setMicActive(token: bigint, active: boolean): Promise<void>;
}
import type { CallRequest as _CallRequest, ExternalBlob as _ExternalBlob, Message as _Message, User as _User, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getCallRequest(arg0: bigint): Promise<CallRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallRequest(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallRequest(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallRequests(): Promise<Array<CallRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallRequests();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallRequests();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessage(arg0: bigint): Promise<Message | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessage(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessage(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getUser(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsersCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersCount();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async verifyUser(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUser();
            return result;
        }
    }

    async registerLocalAccount(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: ExternalBlob | null): Promise<void> {
        const photoArg = arg4 ? candid_some(await this._uploadFile(arg4)) : candid_none();
        const result = await this.actor.registerLocalAccount(arg0, arg1, arg2, arg3, photoArg);
        return result;
    }
    async loginLocalAccount(arg0: string, arg1: string): Promise<bigint> {
        const result = await this.actor.loginLocalAccount(arg0, arg1);
        return result;
    }
    async logoutLocalAccount(arg0: bigint): Promise<void> {
        const result = await this.actor.logoutLocalAccount(arg0);
        return result;
    }
    async validateSessionToken(arg0: bigint): Promise<string | null> {
        const result = await this.actor.validateSessionToken(arg0);
        return result.length === 0 ? null : result[0];
    }
    async getLocalUserProfile(arg0: bigint): Promise<LocalUser | null> {
        const result = await this.actor.getLocalUserProfile(arg0);
        if (result.length === 0) return null;
        const u = result[0];
        return {
            username: u.username,
            displayName: u.displayName,
            passwordHash: u.passwordHash,
            age: u.age,
            photo: u.photo.length === 0 ? undefined : await this._downloadFile(u.photo[0]),
        };
    }
    async updateLocalUserPhoto(arg0: bigint, arg1: ExternalBlob): Promise<void> {
        const uploaded = await this._uploadFile(arg1);
        await this.actor.updateLocalUserPhoto(arg0, uploaded);
    }
    async getLocalUsers(): Promise<Array<LocalUser>> {
        const result = await this.actor.getLocalUsers();
        return Promise.all(result.map(async (u) => ({
            username: u.username,
            displayName: u.displayName,
            passwordHash: u.passwordHash,
            age: u.age,
            photo: u.photo.length === 0 ? undefined : await this._downloadFile(u.photo[0]),
        })));
    }
    async sendDirectMessage(arg0: bigint, arg1: string, arg2: string): Promise<bigint> {
        return await this.actor.sendDirectMessage(arg0, arg1, arg2);
    }
    async getDirectMessages(arg0: bigint, arg1: string): Promise<Array<any>> {
        return await this.actor.getDirectMessages(arg0, arg1);
    }
    async getConversations(arg0: bigint): Promise<Array<any>> {
        return await this.actor.getConversations(arg0);
    }
    async markDirectMessagesRead(arg0: bigint, arg1: string): Promise<void> {
        return await this.actor.markDirectMessagesRead(arg0, arg1);
    }
    async getUnreadDMCount(arg0: bigint): Promise<bigint> {
        return await this.actor.getUnreadDMCount(arg0);
    }
    async sendMessageAsLocal(arg0: bigint, arg1: string): Promise<bigint> {
        return await this.actor.sendMessageAsLocal(arg0, arg1);
    }
    async getMessagesAsLocal(arg0: bigint): Promise<Array<Message>> {
        return await this.actor.getMessagesAsLocal(arg0);
    }
    async createPostAsLocal(arg0: bigint, arg1: string): Promise<bigint> {
        return await this.actor.createPostAsLocal(arg0, arg1);
    }
    async getPostsAsLocal(arg0: bigint): Promise<Array<Post>> {
        return await this.actor.getPostsAsLocal(arg0);
    }
    async deletePostAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.deletePostAsLocal(arg0, arg1);
    }
    async likePostAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.likePostAsLocal(arg0, arg1);
    }
    async unlikePostAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.unlikePostAsLocal(arg0, arg1);
    }
    async getPostLikesAsLocal(arg0: bigint, arg1: bigint): Promise<Array<string>> {
        return await this.actor.getPostLikesAsLocal(arg0, arg1);
    }
    async addCommentAsLocal(arg0: bigint, arg1: bigint, arg2: string): Promise<bigint> {
        return await this.actor.addCommentAsLocal(arg0, arg1, arg2);
    }
    async getCommentsForPostAsLocal(arg0: bigint, arg1: bigint): Promise<Array<Comment>> {
        return await this.actor.getCommentsForPostAsLocal(arg0, arg1);
    }
    async deleteCommentAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.deleteCommentAsLocal(arg0, arg1);
    }
    async joinVoiceChannel(arg0: bigint): Promise<Array<VoiceParticipant>> {
        return await this.actor.joinVoiceChannel(arg0);
    }
    async leaveVoiceChannel(arg0: bigint): Promise<void> {
        return await this.actor.leaveVoiceChannel(arg0);
    }
    async getVoiceParticipants(arg0: bigint): Promise<Array<VoiceParticipant>> {
        return await this.actor.getVoiceParticipants(arg0);
    }
    async sendSignal(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        return await this.actor.sendSignal(arg0, arg1, arg2, arg3);
    }
    async getMySignals(arg0: bigint): Promise<Array<Signal>> {
        return await this.actor.getMySignals(arg0);
    }
    async setMicActive(arg0: bigint, arg1: boolean): Promise<void> {
        return await this.actor.setMicActive(arg0, arg1);
    }
    async sendCallRequestAsLocal(arg0: bigint, arg1: string): Promise<bigint> {
        const result = await this.actor.sendCallRequestAsLocal(arg0, arg1);
        return result;
    }
    async getCallRequestsAsLocal(arg0: bigint): Promise<Array<any>> {
        const result = await this.actor.getCallRequestsAsLocal(arg0);
        return result.map((cr: any) => ({
            id: cr.id,
            callerUsername: cr.callerUsername,
            calleeUsername: cr.calleeUsername,
            status: 'pending' in cr.status ? 'pending' : 'accepted' in cr.status ? 'accepted' : 'denied' in cr.status ? 'denied' : 'ended',
            timestamp: cr.timestamp,
        }));
    }
    async acceptCallRequestAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.acceptCallRequestAsLocal(arg0, arg1);
    }
    async denyCallRequestAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.denyCallRequestAsLocal(arg0, arg1);
    }
    async endCallAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.endCallAsLocal(arg0, arg1);
    }
    async getNotificationsAsLocal(arg0: bigint): Promise<Array<any>> {
        const result = await this.actor.getNotificationsAsLocal(arg0);
        return result.map((n: any) => ({
            id: n.id,
            recipientUsername: n.recipientUsername,
            notifType: 'like' in n.notifType ? 'like' : 'comment' in n.notifType ? 'comment' : 'callRequest',
            actorName: n.actorName,
            postId: n.postId.length > 0 ? n.postId[0] : null,
            postText: n.postText.length > 0 ? n.postText[0] : null,
            callRequestId: n.callRequestId.length > 0 ? n.callRequestId[0] : null,
            timestamp: n.timestamp,
            isRead: n.isRead,
        }));
    }
    async markNotificationReadAsLocal(arg0: bigint, arg1: bigint): Promise<void> {
        return await this.actor.markNotificationReadAsLocal(arg0, arg1);
    }
    async markAllNotificationsReadAsLocal(arg0: bigint): Promise<void> {
        return await this.actor.markAllNotificationsReadAsLocal(arg0);
    }
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_UserProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function from_candid_User_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): Promise<User> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CallRequest]): CallRequest | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n12(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Message | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): Promise<User | null> {
    return value.length === 0 ? null : await from_candid_User_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fname: string;
    name: string;
    photo: [] | [_ExternalBlob];
    telephone: string;
}): Promise<{
    fname: string;
    name: string;
    photo?: ExternalBlob;
    telephone: string;
}> {
    return {
        fname: value.fname,
        name: value.name,
        photo: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.photo)),
        telephone: value.telephone
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fname: string;
    principal: Principal;
    name: string;
    role: _UserRole;
    photo: [] | [_ExternalBlob];
    telephone: string;
}): Promise<{
    fname: string;
    principal: Principal;
    name: string;
    role: UserRole;
    photo?: ExternalBlob;
    telephone: string;
}> {
    return {
        fname: value.fname,
        principal: value.principal,
        name: value.name,
        role: from_candid_UserRole_n16(_uploadFile, _downloadFile, value.role),
        photo: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.photo)),
        telephone: value.telephone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Promise<Array<User>> {
    return await Promise.all(value.map(async (x)=>await from_candid_User_n20(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fname: string;
    name: string;
    photo?: ExternalBlob;
    telephone: string;
}): Promise<{
    fname: string;
    name: string;
    photo: [] | [_ExternalBlob];
    telephone: string;
}> {
    return {
        fname: value.fname,
        name: value.name,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        telephone: value.telephone
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
